### PR TITLE
Use Embind instead of WebIDL

### PR DESCRIPTION
**Pull request by donalffons**
This pull request will implement the bindings to OCCT using Emscripten's Embind instead of the current WebIDL approach.

The advantages:
- All overloaded functions and constructors can be exposed. You don't have to decide which overloads you want to use and / or recompile the library.
- All operators can be exposed.
- The binding code is a bit cleaner and less verbose than with the WebIDL approach (at least for non-overloaded functions).
- It seems like Emscripten offers better error messages now (but that could also be due to an Emscripten update I made).

Code conventions / How-To:
- I wrote down a few ideas on how I would organize and name things (like overloaded functions, overloaded constructors, operators) in [this document](https://github.com/donalffons/opencascade.js/blob/embind/embind/conventions.md).
- Look inside the `embind` folder. Start with [main.cpp](https://github.com/donalffons/opencascade.js/blob/embind/embind/main.cpp) and then look at the header files in that folder.

Current limitations:
- Only a few classes have been exposed so far. However, I wanted to have this pull-request here, so that there is a place to discuss (if there is any need for that...).
- I could not find any solution to generate Typescript types using the Embind workflow. This is a huge drawback at the moment. Currently, I see following options on how to resolve that.
  1. Write the typescript definitions by hand (ew...)
  2. Use something like [cppast](https://github.com/foonathan/cppast) to analyze the OCCT source files and auto-generate typescript bindings from those files. If there is the need for manual adjustments after this step, we might be able to use patch-files?!
  3. Wait until someone else creates a method to generate types from Embind definitions

Other improvements:
- Updated Emscripten
- Updated OCCT
- Updated Python
- Actions push to the respective branch, now

Next steps:
1. Continue to expose all APIs required for running the bottle example and make that work with the new system
2. Expose everything that is currently implemented using WebIDL (also from @zalo's branch)
3. Merge

Any comments would be welcome, particularly from @zalo, @guidovanhilst, @ancorasir, @Johnly1986 (because you guys have actually already used this library :slightly_smiling_face:)

### CODE REVIEW

**Comment by zalo** [comment]
With this technique, would it eventually be possible to expose the entire OpenCascade API... automatically?

If not, this might be a heretical idea, but would it make sense to use the WebIDL to generate the intermediate `embind` exposure interface (the same way that the typescript is generated)?  In that way, you get the benefit of all of the already exposed WebIDL, the typescript definition, AND you get to keep the function overloading...

**Comment by donalffons** [comment]
Yeah, I have been playing around with code-generating the bindings a bit today. First, I looked into `cppast` and `doxygen` but did not have great success with both. Then I came accross [CppHeaderParser](https://pypi.org/project/CppHeaderParser/) and wrote a small [test script](https://github.com/donalffons/opencascade.js/blob/embind/parse.py). Some known issues still remain ([for example](https://github.com/emscripten-core/emscripten/issues/12023#issue-684793557)), but I'm carefully optimistic that this tool might be able to code-generate the bindings automatically. I will do more testing with it and share the results...

If the auto-generation script works, I can have it export Embind and WebIDL bindings and then use the WebIDL file to generate the Typescript definitions. I think that would be pretty neat...

Your suggestion of using WebIDL as the input for the bindings might also work... Probably, I would have to come up with some additional definitions in the IDL file to mark overloaded methods and constructors, so that the Embind bindings and the Typescript definitions can be created correctly from that file.

I'll post here, if I have some updates.

**Comment by donalffons** [comment]
Just a quick update: I now use libclang with Python to generate auto-bindings and it works really well so far. Currently, its generating 11k lines of embind-code (compared to roughly 4k lines in the current IDL file). The embind-code (one line per function) is also much more dense than the IDL code (one line per function argument).
Many things are still missing, but I think we'll get there :slightly_smiling_face:.
(also, I need to investigate why the build is failing...)

**Comment by zalo** [comment]
Awesome work!  The GH Actions logs do make it hard to search (but they added a bar in the top right corner of the UI that helps).

Copied here, the errors look relatively straightforward:
```./bindings.cpp:16569:126: error: no matching constructor for initialization of 'BRepAdaptor_HArray1OfCurve'
      BRepAdaptor_HArray1OfCurve_3(const Standard_Integer theLower, const Standard_Integer theUpper, const int & theValue) : BRepAdaptor_HArray1OfCurve(theLower, theUpper, theValue) {}
                                                                                                                             ^                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```./bindings.cpp:8622:67: error: 'getCellsCount' is a protected member of 'BRepMesh_ConstrainedBaseMeshAlgo'
    .function("getCellsCount", &BRepMesh_ConstrainedBaseMeshAlgo::getCellsCount, allow_raw_pointers())
                                                                  ^
```

So close!

**Comment by donalffons** [comment]
Thanks for pointing that out. I suspect this might be a caching-related issue, since I don't have this problem on my local machine after a fresh rebuild. Probably that's coming from the update to OCCT version 7.4.0.p1.
We're now at almost 50k lines of Embind code :sunglasses: with binary sizes of around 30M. Probably file size will become a major issue eventually. So it might be necessary to split this up into separate modules...
One step at a time :slightly_smiling_face:.

**Comment by donalffons** [comment]
OK, so the previous issues with the failing builds are resolved. I think there were two problems:
1. In the GH action, directory listings gave differently sorted results than on my local machine. It seems like there are some OpenCascade headers, where the sequence of include statements matter (for most of the headers, it does not matter) and inside the GH action, the compiler complained because of undefined symbols due to wrong sequence of include files. I now just sort all include files alphabetically and this solves the issue.
2. I still believe there might have also been a bit of a caching issue

Trying to resolve these kind of bugs on a remote machine is a bit of a pain. I'm just happy that its working now.

The auto-generated binding code is now at just above 100k lines of code with a binary size of 35MB. I'm getting pretty close to be able to run the examples again (not quite there yet, though).

**Comment by donalffons** [comment]
I'm thinking on when and how to merge this... I think it would be best to merge this into master, as soon as
- the examples are working, again
- I created some documentation on how to add / exclude items from the auto-bind system.
- I created some documentation on how to manually add bindings (in case the auto-bind system fails for certain corner cases).

I would also give this a breaking version number on NPM (i.e. 1.x.x). After that merge, the next step would be to bring back typescript support (which will also include comments by the way - because clang is a fantastic C++ parser :slightly_smiling_face:).

@zalo, what do you think about that? It would be your choice if you want to update immediately or if you want to keep using the current version (i.e. 0.x.x. or your own branch) until typescript support is back.

**Comment by zalo** [comment]
Wow!  Comments in the typescript documentation would be incredible! :D

I'd be happy to begin experimenting with the new bindings once you feel like they're ready; Cascade Studio uses a lot more features than the MakeBottle example, so it may take the addition of more features/functionality.

I submitted a new PR back to master (just to resync our WebIDL style branches in terms of functionality); I can handle some of the feature additions if the new process is not too crazy.

**Comment by donalffons** [comment]
Great. I will prepare a short list of open issues, when I find some time. Typescript support will definitely be on there. I believe the new process is really not that crazy :slightly_smiling_face:. But better not look at it just yet. I will clean things up a little bit first and let you know.

**Comment by donalffons** [comment]
Okay, I finally had some time to wrap things up a bit. The examples are now almost working again (some small issues remain in the tessellation code right now), but I will hopefully be able to fix that very soon.

@zalo, if you want to help even more than you already did - any help would be more than welcome. But of course, I don't expect or demand anything.

I wrote down all major open issues that I currently see in a [To-Do](https://github.com/donalffons/opencascade.js/blob/embind/Todo.md) list. From my point of view, 'Typescript & "Intellisense" Support' is currently one of the most important missing features. But other things need to be done as well. And probably, there are some more things that I did not yet think about. The auto-generation of bindings is done by [the autobind.py script](https://github.com/donalffons/opencascade.js/blob/embind/embind/autobind.py). Because the script is not perfect, some bindings are done manually in [this file](https://github.com/donalffons/opencascade.js/blob/embind/embind/manualBindings.h).

Currently, the autobind.py script creates a `bindings.cpp` file in the `build` folder, which is then used by Emscripten. I think for typescript support, the autobind.py file should probably generate another file `index.d.ts`, which contains all typescript definitions.

For parsing the opencascade API definition headers, I'm using libclang in python, which has a similar interface to the [clang](https://clang.llvm.org/doxygen/index.html) C++ library (but not much documentation).

By the way, you might also want to check out the new [build.sh](https://github.com/donalffons/opencascade.js/blob/embind/build.sh) script. I use that, because I keep forgetting the docker build & run commands all the time :-).

**Comment by donalffons** [comment]
Bottle example is fully back in business (in the `embind` branch) :sunglasses: . STEP + IGES loading will follow soon.

**Comment by zalo** [comment]
Awesome stuff! I put together [a test version of Cascade Studio that grabs the Embind bindings straight from this branch](https://cascade-studio-git-feat-embind.zalo.vercel.app/) for quick testing and iteration.

It looks like the toughest thing will be the way overloading is handled...

Since Javascript can inspect the number and type of the incoming arguments, perhaps it makes sense to generate a base-function that routes calls to the correct overload?

```javascript
oc.gp_Pnt = function () {
    if(arguments.length === 0){
        return new oc.gp_Pnt_1();
    } else if(arguments.length === 2){
        return new oc.gp_Pnt_2(arguments[0], arguments[1]);
    } else if(arguments.length === 3){
        return new oc.gp_Pnt_3(arguments[0], arguments[1], arguments[2]);
    }
}
```

**Comment by donalffons** [comment]
Hmm, I don't think that would work universally, i.e. for the entire OpenCascade API, because there is not only overloading by number of arguments (which is supported by JavaScript), but also overloading by type of argument and by return type. Take [BRepLib_MakeEdge](https://git.dev.opencascade.org/gitweb/?p=occt.git;a=blob;f=src/BRepLib/BRepLib_MakeEdge.hxx;h=4b80180dc2e4deda3d490391027aa5354f73748d;hb=33d9a6fa21ca4fa711da7066655aa2ba854545ee) as an example: It has a cool 35 overloads for its constructor, e.g.:
```cpp
// ...
BRepLib_MakeEdge(const gp_Lin& L);
BRepLib_MakeEdge(const gp_Circ& L);
BRepLib_MakeEdge(const gp_Elips& L);
BRepLib_MakeEdge(const gp_Hypr& L);
BRepLib_MakeEdge(const gp_Parab& L);
// ...
```
Well, you could probably create some kind of system, which inspects the Emscripten JavaScript objects and selects the correct overload by type - Emscripten objects have type information attached to them:
image

However, I would be quite scared that this is getting messy, when you're considering inheritance (over multiple levels) and the fact that built-in types between JavaScript and C++ don't match 1:1 (i.e. C++ knows float, double, unsigned int, long int, ... - JavaScript knows only numbers)...

That's why my current feeling is that it might be the best idea to stick with the convention of having each overload suffixed with an underscore and a number (in the order in which they are defined in the OpenCascade header files). At least, this allows you to specify exactly which overload you want to use, like [here](https://github.com/donalffons/opencascade.js-examples/blob/embind/src/demos/bottle%20-%20basic/library.js#L88) - and there is no ambiguity. It might be a bit clunky, but I'm not sure if there is a real alternative to doing it, this way. I also think that "Intellisense" - support help with the development experience a lot, because you don't have to keep the documentation open at all times (and you don't have to manually count to 35 to get the overload you want to have).

Would be happy to hear your thoughts on this.

**Comment by zalo** [comment]
That's true... is it possible to enumerate over the overloads for a particular function somehow?

Perhaps if you try to call a base function or the constructor, it can print out an error message like:
```
Overload not specified for gp_Pnt!  Try one of these overloads:
gp_Pnt_1();
gp_Pnt_2(Standard_Real x, Standard_Real y);
gp_Pnt_3(Standard_Real x, Standard_Real y, Standard_Real z);
```

**Comment by donalffons** [comment]
Hmm, you want to have better error messages, right?! :slightly_smiling_face: 

Maybe this would work? Currently, when I do `new oc.gp_Pnt()`, I get this:
image
That error message is generated by Emscripten, [here](https://github.com/emscripten-core/emscripten/blob/43fcfd2938b72c57373a910ece897b27aa298852/src/embind/embind.js#L1920). Maybe, a simple (?) solution could be to fork Emscripten and then perform some tests to see if constructor_1, constructor_2, ... is `!== undefined` - and then provide a more descriptive error message.

**Comment by zalo** [comment]
Heheh, I think we're looking at the same code.  I just had that section pulled up in a javascript unminifier.

Given that the broader Emscripten project lets you use any overloading naming scheme (and I have no idea how the file is _actually_ organized), I'm investigating just patching in a little code to that function on the CascadeStudio side for now.

**Comment by donalffons** [comment]
Yeah, patching could be a good idea. I'm using some patches for OpenCascade, [here](https://github.com/donalffons/opencascade.js/tree/master/patches). They are applied [here](https://github.com/donalffons/opencascade.js/blob/master/make.py#L152).

**Comment by zalo** [comment]
Hrm, I've gotten surprisingly far with this injection technique, but it doesn't look like the argTypes are persistently stored anywhere I can parse easily...

```javascript
    // Patch in an intelligible overload finding mechanism
    opencascadejsSource = opencascadejsSource.replace('throw new BindingError(name+" has no accessible constructor")', 
      `let message = name + " overload not specified!  Consider using one of these overloads: ";
      let matches = Object.values(registeredPointers).filter((item) => (item.pointerType && item.pointerType.name.includes(legalFunctionName+"_")));
      for(let i = 0; i < matches.length; i++){
        message += matches[i].pointerType.name.slice(0, -1) + "(" + matches[i].pointerType.registeredClass.constructor_body.length-1 +  " args), ";
      }
      throw new BindingError(message);`);
```

It's _sort_ of there in the `constructor_body[0]` function (via the `[[Scopes]]` in the browser inspector), but it requires accessing the enclosing scope of that function, which I don't believe is possible...  (or may require some more injection elsewhere...)

I also tried changing the minimum necessary to get box meshes rendering; it's pretty miserable even with the error helper...

**Comment by donalffons** [comment]
I love it :slightly_smiling_face:! Those error messages are already super helpful. Maybe there is a way of automatically rerouting the calls to the correct overload while still allowing the "hardcore" way of explicitly defining which overload to use for all the (potential) corner cases?!

**Comment by zalo** [comment]
Whew, [Fusion360 disables STEP/IGES export for free users](https://hackaday.com/2020/09/16/autodesk-announces-major-changes-to-fusion-360-personal-use-license-terms/), and the OpenCascade website clobbers two decades of documentation and forum work in just the last couple of days...

Looks like things are heating up for us :)

**Comment by donalffons** [comment]
What? That's pretty nasty from Autodesk. I think it would be great for the whole CAD industry to move more towards web and open source tech. But obviously Autodesk wouldn't share that point of view.

And, yeah, I noticed the same thing about OpenCascade and really freaked out for a moment. That forum (and documentation) that they have is so important for using the library. That new website really doesn't really mention the open-source foundation of all their products, any more.
However, I found today that the old forum is still accessible via https://old.opencascade.com/forums . In fact you can change www.opencascade to old.opencascade and most/all google search results still work. I really hope they fix that (because the internal search of the forum isn't great). And I pray that they don't just take down the forum alltogether.

**Comment by zalo** [comment]
Oh, nice!  That `old` trick is a real life-saver!

**Comment by donalffons** [comment]
I just implemented a simple system which generates a report about all API's that have been exported using the auto-bind script: https://github.com/donalffons/opencascade.js/blob/61adf84544db172f164d55e1703b7fa7eedf2c08/dist/OutputDocumentation.md

Getting there...
:sunglasses:

**Comment by donalffons** [comment]
Hey @zalo, I haven't looked at the CascadeStudio repo for a few days and I was shocked about all the updates you have there. This is insane :slightly_smiling_face:!

**Comment by pentacular** [comment]
Ah, this is great.

I was trying to figure out how much work it would be get around all of the overloaded function problems. :)

Very much appreciate the effort.

**Comment by donalffons** [comment]
Yeah, overloads shouldn't be a problem any more with the next release. This pull request is also really overdue for a merge. I'm just in the process of wrapping everything up. There's currently a weird issue with my build containers turning into zombies after a while. When this is resolved, I will merge it and publish the next release on npm.
Thanks for showing interest!

**Comment by pentacular** [comment]
l tried to build, and clang++ is trying to use a large amount of memory in the emcc phase.

Is this the zombie issue?

**Comment by donalffons** [comment]
Hmm, no, I think the large amount of memory (and the long build time) the project requires isn't really the issue that I'm facing (although it might be related). The zombie-problem is that the docker container which runs the build becomes unresponsive after some time. The build finishes fine (on my machine that takes roughly 2:30 h), the main python script `make.py` exits, but the docker container never finishes. Even trying to `docker stop` or `docker kill` it does nothing. `docker attach` just hangs. Seems like there are quite a few people experiencing this type of issue. I have been trying [tiny](https://github.com/krallin/tini) and `docker run --init` today with no success.

**Comment by zalo** [comment]
The current workflow uploads the build products to github via sequential github actions, but perhaps that step can happen as the last part of the make.py, and then perhaps make.py can also send a signal to github to force deprovision the virtual machine before exiting?  There might even be a way for GitHub to report that the job completed successfully (though I’m just spitballing...)

It’s a shame you only get 7 gigs of RAM to work with in these machines...

**Comment by pentacular** [comment]
I've noticed that where new oc.gp_Pnt(x, y, z) was sufficient, I now need to write new oc.gp_Pnt_3(x, y, z).

Is this expected?

If so, it's probably worth noting in the readme.

**Comment by donalffons** [comment]
@pentacular, yes, this is correct. There are some notes about this in the [embind/conventions.md](https://github.com/donalffons/opencascade.js/edit/embind/embind/conventions.md) document already, but I will also start writing up a brief changelog.

@zalo, It seems like I'm dealing with some sort of [docker-zombie](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) problem. The build's memory consumption is at least 11.5GB, so yeah, the 7GB limit is probably also causing trouble. You suggestion might be a good plan b - I will look into it.

**Comment by zalo** [comment]
Have you considered uncommenting the [if-always under "Upload Build Products"](https://github.com/donalffons/opencascade.js/blob/embind/.github/workflows/main.yml#L82) to see if they're good?

It's also possible to append a timeout for the step like so:
```
      # Build the docker container
      - name: Build OpenCascade.js Bindings
        timeout-minutes: 200
        run: |
          docker run --init \
          -v "$(pwd)/build/":"/opencascade/build/" \
          -v "$(pwd)/dist/":"/opencascade/dist/" \
          -v "$(pwd)/emscripten-cache/":"/emscripten/upstream/emscripten/cache/" \
          my_awesome_image
```

That should shave a couple hours off of the timeout step (timing out at an arbitrarily-chosen 3 hours and 20 minutes).

Not that it's a long-term solution, but it might help with progress...

**Comment by donalffons** [comment]
Hi @zalo, I just merged this into the master branch and created a release tagged with `v1.0.0`. This release is also available on npm.

I gave up on most of the build system, for the moment. As mentioned before, I think (hope) the build system will come back to life when I split up the library into smaller chunks (which can be loaded on demand, allowing for smaller web apps).

I'm sure that there will still be bugs in the library and I would greatly appreciate it if you would report them if you find any.

Next up on my [todo-list](https://github.com/donalffons/opencascade.js/blob/master/Todo.md) are `typescript support` and `modularization`. I think I want to start working on a basic version of the typescript-support first. Once that is working again, I want to look into modularization. Modularization might involve breaking changes, as this could mean that library then must run inside a web-worker (see [here](https://stackoverflow.com/questions/45284788/webassembly-compile-is-disallowed-on-the-main-thread-if-the-buffer-size-is-larg), for example) - except if there is a workaround - need to investigate this more closely. But probably that's not a big issue for CascadeStudio, as you're running OpenCascade inside a web-worker already.

**Comment by zalo** [comment]
Alrighty; I'll look into porting the standard library to use the new embind overload naming scheme; I'll let you know how it goes 👍

**Comment by zalo** [comment]
It doesn't look like inheritance is handled quite the same way... Is there any way to cast types between each other?

Pretty much every time I use `BRepBuilderAPI_MakeEdge`, I use it with a `Handle_Geom_TrimmedCurve`, which is a child class of `Handle_Geom_Curve` (what the  `_24`th constructor expects).  Can I cast TrimmedCurves to Curves?

Also, could I trouble you to add the `oc.BRep_Tool.PolygonOnTriangulation()` function?  [Low Res Model Outlines look funny again without it...](https://cascade-studio-git-feat-embind.zalo.vercel.app/)

**Comment by donalffons** [comment]
> I'll look into porting the standard library to use the new embind overload naming scheme; I'll let you know how it goes

Perfect. If you're making any progress regarding the automatically detecting the correct overload, let me know.
Do you think, I should merge the improved error messages that you worked on, into this project?

> Also, could I trouble you to add the oc.BRep_Tool.PolygonOnTriangulation() function

That should be in the library already (maybe try out the v1.0.1 builds if it doesn't work in v1.0.0). The interface for static methods [changed slightly](https://github.com/donalffons/opencascade.js/blob/master/CHANGELOG.md).

> ... and TColgp_Array1OfPnt constructor?

The build is running. Will let you know when it's done.

**Comment by donalffons** [comment]
New builds are up. Let me know if you need anything else!

**Comment by zalo** [comment]
Thanks!  I must have missed the Triangulation one because my patch only works on Constructors right now...

Unfortunately, the error right after supplying the correct overload of PolygonOnTriangulation is that `TColStd_Array1OfInteger` is unbound [when trying to get the nodes](https://old.opencascade.com/doc/occt-7.1.0/refman/html/class_poly___polygon_on_triangulation.html)...

If it's not a big deal, it would be nice if `TColStd_Array1OfReal` and maybe even `TopTools_ListOfShape` were added too (if it's not already present).

**Comment by donalffons** [comment]
I just implemented bindings for most specializations of the `NCollection_Array1` and `NCollection_List` template classes, i.e. everything that has `*_Array1Of*` or `*_ListOf*` in its name. The only exception being `OpenGl_ListOfStructure`, which Emscripten doesn't like for some reason.
Will post again when the builds have gone through.

**Comment by donalffons** [comment]
...uploaded new builds :v:.

**Comment by zalo** [comment]
It looks like there's an issue where the array got included twice :(

```"BindingError: Cannot register type 'TColQuantity_Array1OfLength' twice
    at Object.<anonymous> (blob:http://127.0.0.1:5500/7df7cdaf-8d22-4c99-a558-6d311fa95836:11:86851)
    at new <anonymous> (blob:http://127.0.0.1:5500/7df7cdaf-8d22-4c99-a558-6d311fa95836:11:86668)
    at throwBindingError (blob:http://127.0.0.1:5500/7df7cdaf-8d22-4c99-a558-6d311fa95836:11:87292)
    at registerType (blob:http://127.0.0.1:5500/7df7cdaf-8d22-4c99-a558-6d311fa95836:11:88806)
    at onComplete (blob:http://127.0.0.1:5500/7df7cdaf-8d22-4c99-a558-6d311fa95836:11:87792)
    at whenDependentTypesAreResolved (blob:http://127.0.0.1:5500/7df7cdaf-8d22-4c99-a558-6d311fa95836:11:88352)
    at __embind_register_class (blob:http://127.0.0.1:5500/7df7cdaf-8d22-4c99-a558-6d311fa95836:11:104447)
    at <anonymous>:wasm-function[83378]:0x35abbc2
    at Bo (<anonymous>:wasm-function[83379]:0x35c38f9)
    at Module.___wasm_call_ctors (blob:http://127.0.0.1:5500/7df7cdaf-8d22-4c99-a558-6d311fa95836:23:89833)"
```

**Comment by zalo** [comment]
(oops, sorry, Github formatting clobbered the actual error before, it's been edited to include it now)

**Comment by donalffons** [comment]
Thanks for that. Yeah, I agree that testing would be good to have testing. I will put that on my list...

I'm running another build which will hopefully work better.

**Comment by donalffons** [comment]
Can you try the new builds? Bottle example is working fine, here.

**Pull request merged**
