### PR TITLE
Add Github Actions Build and Fix Regressions

### PR DESCRIPTION
**Pull request by zalo**
This PR sets up a Github Action that automatically builds the opencascade.js library upon each push, and pushes the resulting build products in `dist` back to master.  It takes about 2 hours and 45 minutes to build the first time, and then about 25 minutes each subsequent time (since it is able to lean on the cache).

The PR also exposes some new functionality relating to Trasnsforms in the IDL, which enable moving, scaling, and rotating objects (common OpenSCAD operations).  There are also improvements for Intersection Booleans, MakePrism, a few 2D edge definition commands, and more (though I wasn't able to get PolygonOnTriangulation to return anything, so the outlines are mismatched from the mesh unfortunately :( ).

On the line where the workflow logs into the Github Package Registry, you'll probably want to change my username to yours.

Please ignore/squash the commit history in the merge; it turns out that once you have a working CI system you tend to use it to test changes in broad daylight 🙃 

These changes are live in the editor at https://zalo.github.io/CascadeStudio/

### CODE REVIEW

**Comment by zalo** [comment]
The emscripten update broke the buil with the cached intermediates, so let's see if a totally fresh build (done in 2.75 hours) will resolve those issues...
https://github.com/zalo/opencascade.js/runs/915804794?check_suite_focus=true

**Comment by donalffons** [comment]
Awesome, this is beautiful! :-)

> It takes about 2 hours and 45 minutes to build the first time, and then about 25 minutes each subsequent time (since it is able to lean on the cache).

Yup, 25 minutes isn't bad at all. 

> The PR also exposes some new functionality relating to Trasnsforms in the IDL [...]

Perfect, thanks. I also noticed that you fixed one of the regressions I introduced recently. I accidentally changed the type of one of the parameters of the constructor of `BRepPrimAPI_MakePrism`. That lead to the bottle-example not working anymore and Emscripten's error message was `uncaught exception` and honestly pretty useless to me. It took me extremely long to track this down. I think this should work much better when using typescript. I was thinking of changing the examples to also use typescript..? Although keeping them as _plain JavaScript_ as possible would probably also be desirable... But I digress :-).

> though I wasn't able to get PolygonOnTriangulation to return anything, so the outlines are mismatched from the mesh unfortunately :(

OK, I get it... That's why the edges look _rough_ in CascadeStudio. Would be great if we can get this to work eventually. A quick fix is probably to bump up the resolution of the mesh + edges, but that's obviously not a good solution. I might also look into the issue, when I have time.

> On the line where the workflow logs into the Github Package Registry, you'll probably want to change my username to yours.

Thanks, will try that out, now.

> it turns out that once you have a working CI system you tend to use it to test changes in broad daylight

Yeah, that actually looks exactly like what I'm doing every time I have to do something with a CI/CD system. I feel your pain :-). Really great that this is working now!

**Comment by zalo** [comment]
I don't have strong feelings about typescript one way or another, but I did find it handy enough to enable in CascadeStudio to validate input arguments for the simplified wrapper library I'm writing on top of the base opencascade functionality.

Also I did eventually fix the PolygonOnTriangulation thing; you may need to hit "Reset Project" in order to see it!

Edge visualization is handy for MouseOver highlighting to get their indices... to create targeted fillets!  Here are some fun fillet gifs:
Fillets
FilletsLimits

**Comment by donalffons** [comment]
> The emscripten update broke the build with the cached intermediates [...]

Hmm, yeah, in the case of am Emscripten update, we probably want to clear all caches (especially the folders `emscripten-cache` and `build`), to be sure that there are no errors from mixing version, right?! You certainly know much better, what and how to do this... I will double-check that the github builds match with the ones I make locally.

**Comment by donalffons** [comment]
> Here are some fun fillet gifs

Holy cow! :-D This running in real time?! That's very promising :-)

**Comment by zalo** [comment]
It's not suuuper slow; you can even try it yourself now since I added URL serialization:
[CascadeStudio Fillet Test](https://zalo.github.io/CascadeStudio/?code=RY7NCsIwDIDve4qwUwdRuomHMeZB0QfQeZCxw36KFGoLXQcT8d1N56YhhBC%2BL4kSDpxUDqbI4aJkJywLC5qFCBwQVomvCUdwdhBRFihyGjPC4hS21r2qnWAlQZQx5xXC3oyMOoTtNJr12W%2BfSmq6dCP%2FbNwsx%2BhF%2Fw%2FCYSaYVxPOf6Z5NMvlq5ZGs5Kewf%2FGisDgJBXBx%2B4ueuYNhBSBeWCMIN%2FBywo3WA1livGmWkvdqqEj9ktk7yj7AA%3D%3D&gui=q1ZKzs8tyM9LzSvxS8xNVbJSSk4sTk5MSQ3LTC1X0lHyTS3OCEotVrIy0LMwgXODEvPSgWqjDfQMDHUMY3WUQjJzSpSsdI30LI0hHJgKXSMDHSOD2FoA)

This should also make it easier to point out working or broken functionality in the API as it comes up.

**Comment by donalffons** [comment]
URL serialization is a great addition and will make it very easy to share examples.

> It's not suuuper slow

I think the speed is really good in this example. Eventually, I would like to do some benchmarking to see where performance can be improved. Boolean operations seem to be quite expensive in OpenCascade. I'm also pretty sure that the current tessellation code is less than optimal :-).

Hey, by the way, it seems like there is a bit of z-fighting going on between the edges and the faces. You might be able to solve that using the `[polygonOffset](https://threejs.org/docs/#api/en/materials/Material.polygonOffset)` property (probably best to use that on the edge material). I think the way how that works is that materials with a polygonOffset get pushed slightly in front of other materials in the depth buffer. More info is [here](https://github.com/mrdoob/three.js/issues/2593).

**Comment by zalo** [comment]
Nice spot on that property!  I was looking for something like that earlier, and definitely missed this.

I’ll investigate adding it!

**Pull request merged**
