### PR TITLE
Add Typescript & "Intellisense" Support

### PR DESCRIPTION
**Pull request by donalffons**
* Auto-Generate types for auto-generated bindings
* Allow for manual definitions of types for manually defined bindings
* Add comments to typescript definitions

[Todo.md](https://github.com/donalffons/opencascade.js/blob/master/Todo.md)

### CODE REVIEW

**Comment by donalffons** [comment]
Hi @zalo, in case you're interested: Initial typescript + intellisense support is now working. I will do more testing and eventually merge this into `master` and `lite`.

Some typings are currently unsupported (e.g. function pointers, template base classes without typedefs, template arguments without typedefs, ...). But generally, I think this will be a good improvement to the library.

**Comment by zalo** [comment]
That's awesome!  This will be super nice to have when working with the raw API.

**Comment by veggielane** [comment]
I would love to be able to get this working nicely with Deno!

**Comment by donalffons** [comment]
> I would love to be able to get this working nicely with Deno!

Do you want to get typescript + intellisense working? Or are you having trouble with the library in general? For me, the library does work well inside a NodeJS environment when I import it using `import opencascade from 'opencascade.js/dist/opencascade.wasm'` and use babel to transpile ES6 import / export syntax (maybe there is a more user-friendly way of doing this... but I haven't had time to look deeper into that subject, yet). However, the typescript support doesn't work in this case. But I will fix that soon.

**Comment by veggielane** [comment]
> > I would love to be able to get this working nicely with Deno!
> 
> Do you want to get typescript + intellisense working? Or are you having trouble with the library in general? For me, the library does work well inside a NodeJS environment when I import it using `import opencascade from 'opencascade.js/dist/opencascade.wasm'` and use babel to transpile ES6 import / export syntax (maybe there is a more user-friendly way of doing this... but I haven't had time to look deeper into that subject, yet). However, the typescript support doesn't work in this case. But I will fix that soon.

My use case is more scripting so a deno/node environment is more preferable. I also used Babel to transpile, but yeah it's not that user friendly

**Comment by donalffons** [comment]
...this functionality will be integrated slightly differently with the upcoming modularization builds.

**Pull request closed without merging**
